export const data = [
  {
    _id: "hnf2348rth341298",
    type: "Alert",
    user: "fji43oj3902",
    name: "Test Alert 1",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 1,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
  {
    _id: "48rth34128",
    type: "Alert",
    user: "ce3902",
    name: "Test Alert 2",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 2,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
  {
    _id: "4232348rth341298",
    type: "Alert",
    user: "fji44miko3oj3902",
    name: "Test Alert 3",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 3,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
  {
    _id: "231f2348fkmornwe341298",
    type: "Alert",
    user: "___3902",
    name: "Test Alert 4",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 4,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
  {
    _id: "2sxqjkn48rth341298",
    type: "Alert",
    user: "124123412",
    name: "Test Alert 5",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 5,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
];
