export const data = [
  {
    _id: "1",
    type: "Alert",
    user: "fji43oj3902",
    name: "Test Alert 1",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 1,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
  {
    _id: "2",
    type: "Alert",
    user: "ce3902",
    name: "Test Alert 2",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 2,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
  {
    _id: "3",
    type: "Alert",
    user: "fji44miko3oj3902",
    name: "Test Alert 3",
    requiredValue: 1,
    operator: "Equal",
    triggeredTimes: 3,
    active: true,
    eventValidityUnix: 49378124,
    testMode: false,
    isMarketProvider: false,
    alert: {
      provider: "Trading View",
    },
  },
  // {
  //   _id: "4",
  //   type: "Alert",
  //   user: "___3902",
  //   name: "Test Alert 4",
  //   requiredValue: 1,
  //   operator: "Equal",
  //   triggeredTimes: 4,
  //   active: true,
  //   eventValidityUnix: 49378124,
  //   testMode: false,
  //   isMarketProvider: false,
  //   alert: {
  //     provider: "Trading View",
  //   },
  // },
  // {
  //   _id: "5",
  //   type: "Alert",
  //   user: "124123412",
  //   name: "Test Alert 5",
  //   requiredValue: 1,
  //   operator: "Equal",
  //   triggeredTimes: 5,
  //   active: true,
  //   eventValidityUnix: 49378124,
  //   testMode: false,
  //   isMarketProvider: false,
  //   alert: {
  //     provider: "Trading View",
  //   },
  // },
];
